services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: example_admin
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: prisma_db
    ports:
      - 5432:5432

  queue:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
